### ISSUE TITLE
Namespaces throw a 500

### ISSUE THREAD

**Issue by stmishra** [Talentica/laravel-sample-app#4]
Checkout the branch 'namespaces'. Adding a namespace to the controller throws a 500.

Tried adding psr-4 autoloading in composer, and other tricks. All our classes should have a namespace - we need to fix this and merge back to master.

**Comment by stmishra** [comment]
Assigning to Piyush since I am no expert in psr-4 and php autoloads.

**Comment by chetanism** [comment]
This was fixed by dac95a215c711bfdaf8296c6c6885191378b305f and ecddafd6a09d1b79fe7ac42e9ba6dc1df0f4b805
